environment:
  APPVEYOR_VNC_BLOCK: true
image:
- macos-mojave
build_script:
- sh: sleep 1d
install:
- sh: HOMEBREW_NO_AUTO_UPDATE=1 brew install create-dmg
on_finish:
- sh: export APPVEYOR_VNC_BLOCK=true
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
